In [1]:
## Import

%matplotlib inline
import numpy as np
import pandas as pd
import os
import urllib.request
import datetime
import gzip
import shutil
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
from sklearn import preprocessing
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from math import cos, asin, sqrt
import datetime
import sklearn
import sys

listing_col  = ['id', ## om het nog te traceren
               'host_id',## om het nog te traceren
               'listing_url',
               'name',
               'price',
#                'summary', ## Heel vaak niet gevuld, heeft te veel invloed op het uiteindelijke resultaat
               'host_name',
#                'host_about',
               'description',
               'neighbourhood_cleansed', # om het nog te aggrereen
#                'property_type',
               'room_type',
               'beds',
               'bedrooms',
               'bathrooms',
               'accommodates',
               'latitude',  # nog even erin laten
               'longitude'  # nog even erin laten
              ]

In [2]:
##Handige cell om inzicht in groote van objecten te weergeven

sorted([(x, sys.getsizeof(globals().get(x))) for x in dir() if not x.startswith('_') and x not in sys.modules], key=lambda x: x[1], reverse=True)

[('TfidfVectorizer', 1056),
 ('Out', 240),
 ('listing_col', 184),
 ('cosine_similarity', 136),
 ('linear_kernel', 136),
 ('In', 96),
 ('np', 80),
 ('pd', 80),
 ('preprocessing', 80),
 ('sparse', 80),
 ('asin', 72),
 ('cos', 72),
 ('sqrt', 72),
 ('get_ipython', 64),
 ('exit', 56),
 ('quit', 56)]

## Loading all the data of 2018


url = 'http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2018-01-10/data/listings.csv.gz'
filename = 'listings_2018-01-10.csv.gz'
urllib.request.urlretrieve(url, filename)
unfilled = gzip.open(filename)
df_listings = pd.read_csv(unfilled, usecols=listing_col)
df_listings['publicatie'] = '2018-01-10'
item = "listings" 
            

our_dates= []
start = datetime.datetime.strptime("11-01-2018", "%d-%m-%Y")  # we can change this
end = datetime.datetime.strptime("31-12-2018", "%d-%m-%Y")    # we can change this
date_generated = [start + datetime.timedelta(days=x) for x in range(0, (end-start).days)]

for date in date_generated:
    our_dates.append(date.strftime("%Y-%m-%d"))

for date in our_dates:
    url = "http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/" +date+ "/data/"+item+".csv.gz"
    filename = item +"_"+ date +".csv.gz" 
    file_python = item +"_"+ date
    try:
        urllib.request.urlretrieve(url, filename)
        print("found : " + date)
        unfilled = gzip.open(filename)
#         df_reviews[file_python] = pd.read_csv(unfilled)
        temp = pd.read_csv(unfilled, usecols=listing_col)
        temp['publicatie'] = date
        
        df_listings.append(temp)
        
        
    except urllib.error.URLError as e:
        print(e.reason)

## Loading only one run

In [3]:
url = 'http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2019-01-13/data/listings.csv.gz'
filename = 'listings_2019-01-13.csv.gz'
urllib.request.urlretrieve(url, filename)
unfilled = gzip.open(filename)
df_listings = pd.read_csv(unfilled, usecols=listing_col)
# df_listings['publicatie'] = '2019-01-13'

del unfilled

## Set verdeelsleutel

In [4]:
verdeelsleutel_description        =0.4
verdeelsleutel_name               =0.1
verdeelsleutel_price              =0.05
verdeelsleutel_location           =0.05
verdeelsleutel_listing_attributes =0.05
# 40%, name 10%, price 5%, location 40%, amenities 5

## Cleansing

In [5]:
print_helper = list(range(0, len(df_listings), 1000))
df_listings['bedrooms'].fillna((df_listings['bedrooms'].mean()), inplace=True)
df_listings['beds'].fillna((df_listings['beds'].mean()), inplace=True)
df_listings['bathrooms'].fillna((df_listings['bathrooms'].mean()), inplace=True)
df_listings['price'] = pd.to_numeric(df_listings['price'].str.replace(',','').str.replace('$',''))
df_listings.description = df_listings.description.fillna('')
df_listings.host_name = df_listings.host_name.fillna('')
df_listings.name = df_listings.name.fillna('')

## Column Description and Name

In [6]:
def tfidf_cosine_function (columname, listing_id_column, verdeel_sleutel= 1):
    """ This function turns a non numerical column into a cosine simalartiy matrix using tfidf """
    
    tfidf = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf.fit_transform(columname)

    cosine_simalarity_array = linear_kernel(tfidf_matrix,tfidf_matrix)
    np.fill_diagonal(cosine_simalarity_array, 0)
    output = pd.DataFrame(cosine_simalarity_array)
    output.rename(index=listing_id_column , inplace = True)
    output.rename(columns= listing_id_column, inplace = True)
    del cosine_simalarity_array      
    return output * verdeel_sleutel

In [7]:
description =tfidf_cosine_function(df_listings.description, df_listings.id,verdeelsleutel_description )
name        =tfidf_cosine_function(df_listings.name, df_listings.id , verdeelsleutel_name)

## Column Listing attributes

In [8]:
# Memommery issues door amnestiesen propertytype
listing_attributes = df_listings[['accommodates','bathrooms','bedrooms','beds', 'room_type']]
listing_attributes =pd.get_dummies(listing_attributes, columns=['room_type'])
cosine_simalarity_array = cosine_similarity(listing_attributes,listing_attributes)
np.fill_diagonal(cosine_simalarity_array, 0)
listing_attributes = pd.DataFrame(cosine_simalarity_array * verdeelsleutel_listing_attributes)
listing_attributes.rename(index= df_listings.id , inplace = True)
listing_attributes.rename(columns= df_listings.id, inplace = True)
del cosine_simalarity_array

## Column Location

In [9]:
def distance(lat1, lon1, lat2, lon2):
    p = 0.017453292519943295     #Pi/180
    a = 0.5 - cos((lat2 - lat1) * p)/2 + cos(lat1 * p) * cos(lat2 * p) * (1 - cos((lon2 - lon1) * p)) / 2
    return 12742 * asin(sqrt(a)) #2*R*asin...

# distance(52.36755,4.9414,53.390225,4.873924) ## voorbeeldje

tuple_set = list(zip(df_listings.latitude, df_listings.longitude)) ## list met alle tuples

matrix = np.zeros((len(tuple_set), len(tuple_set))) ## iniatilize the array

for i in range(len(tuple_set)):  
    for j in range(len(tuple_set)):
        matrix[i][j] = abs(distance(*tuple_set[i], *tuple_set[j]))
    if i in print_helper:
        print("Bezig met row ", i, "van de ", len(tuple_set), "current time: ",datetime.datetime.now())

        
loc = sklearn.preprocessing.minmax_scale(matrix, feature_range=(0, 1), axis=1, copy=True)
location = [1] - loc
np.fill_diagonal(location, 0)
location = pd.DataFrame(location * verdeelsleutel_location)       
location.rename(index= df_listings.id , inplace = True)
location.rename(columns= df_listings.id, inplace = True)

del distance
del matrix
del loc
del tuple_set

Bezig met row  0 van de  19910 current time:  2019-01-18 13:45:29.530769
Bezig met row  1000 van de  19910 current time:  2019-01-18 13:45:59.146502
Bezig met row  2000 van de  19910 current time:  2019-01-18 13:46:28.109258
Bezig met row  3000 van de  19910 current time:  2019-01-18 13:46:56.173266
Bezig met row  4000 van de  19910 current time:  2019-01-18 13:47:24.264174
Bezig met row  5000 van de  19910 current time:  2019-01-18 13:47:52.285661
Bezig met row  6000 van de  19910 current time:  2019-01-18 13:48:21.099653
Bezig met row  7000 van de  19910 current time:  2019-01-18 13:48:49.160787
Bezig met row  8000 van de  19910 current time:  2019-01-18 13:49:17.134925
Bezig met row  9000 van de  19910 current time:  2019-01-18 13:49:44.749480
Bezig met row  10000 van de  19910 current time:  2019-01-18 13:50:13.205154
Bezig met row  11000 van de  19910 current time:  2019-01-18 13:50:41.544402
Bezig met row  12000 van de  19910 current time:  2019-01-18 13:51:09.980308
Bezig met row  13000 van de  19910 current time:  2019-01-18 13:51:38.553944
Bezig met row  14000 van de  19910 current time:  2019-01-18 13:52:06.713171
Bezig met row  15000 van de  19910 current time:  2019-01-18 13:52:34.463217
Bezig met row  16000 van de  19910 current time:  2019-01-18 13:53:02.326442
Bezig met row  17000 van de  19910 current time:  2019-01-18 13:53:30.136180
Bezig met row  18000 van de  19910 current time:  2019-01-18 13:53:57.542700
Bezig met row  19000 van de  19910 current time:  2019-01-18 13:54:25.156264

## Column Price

In [10]:
extractedData = df_listings.loc[:,['price']].values


# Uitgezet wegens performance redenen
# for i in range(1,len(extractedData)):
#     newrow = abs(extractedData.T - extractedData[i])
#     A = np.vstack([A, newrow])
#     if i in print_helper:
#         print("Bezig met row ", i, "van de ", len(extractedData), "current time: ",datetime.datetime.now())

matrix2 = np.zeros((len(extractedData), len(extractedData))) ## iniatilize the array
        
for i in range(len(extractedData)):  
    for j in range(len(extractedData)):
        matrix2[i][j] = abs(extractedData[i] - extractedData[j])
    if i in print_helper:
        print("Bezig met row ", i, "van de ", len(extractedData), "current time: ",datetime.datetime.now())

price = sklearn.preprocessing.minmax_scale(matrix2, feature_range=(0, 1), axis=1, copy=True)
price = [1] - price
np.fill_diagonal(price, 0)
price = pd.DataFrame(price * verdeelsleutel_price)  
price.rename(index= df_listings.id , inplace = True)
price.rename(columns= df_listings.id, inplace = True)

del matrix2
del extractedData

Bezig met row  0 van de  19910 current time:  2019-01-18 13:55:16.856068
Bezig met row  1000 van de  19910 current time:  2019-01-18 13:55:47.611661
Bezig met row  2000 van de  19910 current time:  2019-01-18 13:56:18.928142
Bezig met row  3000 van de  19910 current time:  2019-01-18 13:56:48.877009
Bezig met row  4000 van de  19910 current time:  2019-01-18 13:57:18.616469
Bezig met row  5000 van de  19910 current time:  2019-01-18 13:57:49.064375
Bezig met row  6000 van de  19910 current time:  2019-01-18 13:58:19.807278
Bezig met row  7000 van de  19910 current time:  2019-01-18 13:58:49.006369
Bezig met row  8000 van de  19910 current time:  2019-01-18 13:59:18.399703
Bezig met row  9000 van de  19910 current time:  2019-01-18 13:59:47.550773
Bezig met row  10000 van de  19910 current time:  2019-01-18 14:00:16.995603
Bezig met row  11000 van de  19910 current time:  2019-01-18 14:00:46.285541
Bezig met row  12000 van de  19910 current time:  2019-01-18 14:01:15.333779
Bezig met row  13000 van de  19910 current time:  2019-01-18 14:01:46.170495
Bezig met row  14000 van de  19910 current time:  2019-01-18 14:02:16.819643
Bezig met row  15000 van de  19910 current time:  2019-01-18 14:02:49.491165
Bezig met row  16000 van de  19910 current time:  2019-01-18 14:03:22.061467
Bezig met row  17000 van de  19910 current time:  2019-01-18 14:03:51.487780
Bezig met row  18000 van de  19910 current time:  2019-01-18 14:04:21.558273
Bezig met row  19000 van de  19910 current time:  2019-01-18 14:04:51.005660

## Add all the frames together in one frame

In [11]:
# Helaas loop ik tegen memomery issues aan, daarom verwijder ik de helft van elke frame, deze zou daarna opnieuw gedraaid moeten worden

eerste_helft = 0
tweede_helft = 0
derde_helft  = 1

if eerste_helft == 1:
    description        = description.iloc[0:8000,:]
    price              = price.iloc[0:8000,:]
    listing_attributes = listing_attributes.iloc[0:8000,:]
    location           = location.iloc[0:8000,:]
    name               = name.iloc[0:8000,:]

if tweede_helft == 1:
    description        = description.iloc[8000:15000,]
    price              = price.iloc[8000:15000,]
    listing_attributes = listing_attributes.iloc[8000:15000,]
    location           = location.iloc[8000:15000,]
    name               = name.iloc[8000:15000,]

if derde_helft == 1:
    description        = description.iloc[15000:,:]
    price              = price.iloc[15000:,:]
    listing_attributes = listing_attributes.iloc[15000:,:]
    location           = location.iloc[15000:,:]
    name               = name.iloc[15000:,:]

In [12]:
# result = description + name + price + location + listing_attributes
result = description.add(name)
result = result.add(location)
result = result.add(price)
result = result.add(listing_attributes)

## Selecting the highest score per id

In [13]:
best_matching_id = result.idxmax()
match_value = result.max(axis=1)
# del result
match = pd.DataFrame({'best_matching_id':best_matching_id, 'match_value':match_value})
match =match.sort_values(by=['match_value'], ascending=False)
match_df = match.sort_values(by=['match_value'], ascending=False).reset_index()
match_df.rename(columns = {'index':'id'}, inplace = True)

## Enkel de matches overhouden met match_value > 70
match_df = match_df[match_df['match_value'] > 0.7]

## Only to show the urls

result = pd.merge(match_df,
                 df_listings[['id', 'listing_url', 'host_id']],
                 on='id')
result.head()

result = pd.merge(result,
                 df_listings[['id', 'listing_url', 'host_id']],
                 left_on='best_matching_id', right_on = 'id')


result.head()

result_filter = result[result.host_id_x != result.host_id_y]

def make_clickable(val):
    # target _blank to open new window
    return '<a target="_blank" href="{}">{}</a>'.format(val, val)


result_filter = result_filter.sort_values(by=['match_value'], ascending=False)
result_filter.style.format({'listing_url_x': make_clickable,'listing_url_y': make_clickable })

In [14]:
# Find corresponding feature contributions
list_holder_attr  = []
list_holder_price = []
list_holder_name  = []
list_holder_desc  = []
list_holder_loc   = []

for index, row in match_df.iterrows():
    idnr = row['id']
    best_match = row['best_matching_id']
    list_holder_price.append(round(price.loc[idnr,best_match]/verdeelsleutel_price,3))
    list_holder_loc.append(round(location.loc[idnr,best_match]/verdeelsleutel_location,3))
    list_holder_name.append(round(name.loc[idnr,best_match]/verdeelsleutel_name,3))
    list_holder_attr.append(round(listing_attributes.loc[idnr,best_match]/verdeelsleutel_listing_attributes,3))
    list_holder_desc.append(round(description.loc[idnr,best_match] / verdeelsleutel_description,3))

In [15]:
match_df['feature_listing_attributes'] = list_holder_attr
match_df['feature_price'] = list_holder_price 
match_df['feature_name'] = list_holder_name  
match_df['feature_description'] = list_holder_desc  
match_df['feature_location'] = list_holder_loc   
match_df['duplicate_ID'] = range(1, len(match_df) + 1)
match_df['type']  = 'listings'
match_df['status']  = 'Undifined'
match_df['timestamp'] = "13-01-2019"
match_df.rename(columns = {'id':'case_A_id','best_matching_id':'case_B_id','match_value':'match_score'}, inplace = True)
output =match_df[["duplicate_ID","type","case_A_id","case_B_id","match_score", "status", "timestamp", "feature_listing_attributes",'feature_price','feature_name','feature_location','feature_description']]

In [16]:
y_cond = (output.case_A_id.shift(1) == output.case_B_id)
output['Result'] = np.where(y_cond, 'Y', 'N')
output = output[output['Result']== 'Y' ]
output =output.iloc[:,:-1]  ## Remove the result column , which indicates if their is a dubblicate match

C:\Users\Jeffr\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [17]:
output

,duplicate_ID,type,case_A_id,case_B_id,match_score,status,timestamp,feature_listing_attributes,feature_price,feature_name,feature_location,feature_description
1,2,listings,22556265,22556393,0.999898,Undifined,13-01-2019,1.000,1.000,1.000,0.998,1.000
3,4,listings,25177209,30976179,0.999879,Undifined,13-01-2019,1.000,1.000,1.000,0.998,1.000
8,9,listings,23500074,31150995,0.999458,Undifined,13-01-2019,1.000,1.000,1.000,0.989,1.000
10,11,listings,31146480,28688750,0.999409,Undifined,13-01-2019,1.000,1.000,1.000,0.989,1.000
12,13,listings,23061996,23880524,0.999402,Undifined,13-01-2019,1.000,1.000,1.000,0.988,1.000
14,15,listings,29097516,29096046,0.999373,Undifined,13-01-2019,1.000,0.997,1.000,0.990,1.000
16,17,listings,23777372,23626417,0.999358,Undifined,13-01-2019,1.000,1.000,1.000,0.987,1.000
20,21,listings,30531957,24978557,0.999334,Undifined,13-01-2019,1.000,1.000,1.000,0.987,1.000
25,26,listings,23956368,26943704,0.999231,Undifined,13-01-2019,1.000,0.996,1.000,0.988,1.000
28,29,listings,23855455,24417774,0.999101,Undifined,13-01-2019,0.988,0.999,1.000,0.995,1.000
30,31,listings,23874962,24036014,0.998975,Undifined,13-01-2019,1.000,0.994,1.000,0.986,1.000
33,34,listings,25373341,29196220,0.998867,Undifined,13-01-2019,1.000,1.000,1.000,0.977,1.000
37,38,listings,22607144,29677382,0.997702,Undifined,13-01-2019,0.988,0.997,1.000,0.969,1.000
39,40,listings,29836165,30514273,0.997575,Undifined,13-01-2019,1.000,1.000,0.981,0.989,1.000
41,42,listings,23606060,23611578,0.997351,Undifined,13-01-2019,0.971,0.995,1.000,0.981,1.000
43,44,listings,23610398,29817319,0.996709,Undifined,13-01-2019,0.971,1.000,1.000,0.963,1.000
47,48,listings,26724522,26724213,0.995649,Undifined,13-01-2019,1.000,1.000,0.960,0.992,1.000
52,53,listings,30851016,31138342,0.990663,Undifined,13-01-2019,1.000,0.980,1.000,0.991,0.989
54,55,listings,27276546,27304181,0.989977,Undifined,13-01-2019,1.000,0.998,1.000,0.988,0.988
56,57,listings,30953082,30883680,0.989451,Undifined,13-01-2019,1.000,1.000,0.895,0.999,1.000
58,59,listings,26099813,23777651,0.989116,Undifined,13-01-2019,1.000,1.000,1.000,0.997,0.986
61,62,listings,26912817,23073644,0.987389,Undifined,13-01-2019,1.000,0.998,0.880,0.990,1.000
64,65,listings,24780142,24772269,0.986556,Undifined,13-01-2019,1.000,0.996,0.876,0.982,1.000
66,67,listings,24508265,24507945,0.984628,Undifined,13-01-2019,1.000,1.000,0.848,0.997,1.000
69,70,listings,29673658,26506810,0.983853,Undifined,13-01-2019,1.000,1.000,0.840,0.996,1.000
72,73,listings,24594713,24603567,0.983628,Undifined,13-01-2019,1.000,0.997,1.000,0.992,0.979
77,78,listings,24732648,24628192,0.980463,Undifined,13-01-2019,1.000,1.000,0.812,0.985,1.000
83,84,listings,27566962,27399582,0.976606,Undifined,13-01-2019,0.949,1.000,0.797,0.989,1.000
85,86,listings,28508559,28510636,0.975672,Undifined,13-01-2019,1.000,1.000,0.766,0.981,1.000
87,88,listings,30313908,30194200,0.975478,Undifined,13-01-2019,1.000,1.000,0.758,0.994,1.000
...,...,...,...,...,...,...,...,...,...,...,...,...
685,686,listings,25183743,27466535,0.759284,Undifined,13-01-2019,1.000,1.000,0.000,0.997,0.813
693,694,listings,30554026,30553840,0.756685,Undifined,13-01-2019,1.000,0.997,0.794,0.991,0.704
696,697,listings,25881265,28269732,0.756061,Undifined,13-01-2019,0.962,1.000,0.138,0.970,0.794
700,701,listings,30785761,30778548,0.753492,Undifined,13-01-2019,1.000,0.991,1.000,0.994,0.672
702,703,listings,23364006,26314462,0.753425,Undifined,13-01-2019,0.901,0.994,0.739,0.990,0.714
704,705,listings,23737882,31120235,0.753177,Undifined,13-01-2019,0.932,0.996,0.121,0.963,0.795
706,707,listings,23407066,28021557,0.752189,Undifined,13-01-2019,1.000,0.998,0.157,0.940,0.786
719,720,listings,22448278,22448502,0.742938,Undifined,13-01-2019,1.000,0.994,0.510,0.997,0.723
725,726,listings,27362571,27600742,0.735773,Undifined,13-01-2019,0.821,0.990,0.198,0.993,0.768
728,729,listings,27367035,27333979,0.735160,Undifined,13-01-2019,1.000,0.996,0.862,0.986,0.667
730,731,listings,23897024,24027533,0.734581,Undifined,13-01-2019,0.814,0.986,0.791,0.991,0.688
734,735,listings,30877597,24567873,0.733487,Undifined,13-01-2019,1.000,0.998,0.302,0.990,0.739
736,737,listings,27760990,29176969,0.732515,Undifined,13-01-2019,1.000,1.000,0.097,0.985,0.765
741,742,listings,25897763,27100241,0.730061,Undifined,13-01-2019,1.000,0.993,0.878,0.985,0.658
743,744,listings,30057249,31095269,0.729934,Undifined,13-01-2019,0.896,0.993,0.702,0.993,0.687
746,747,listings,29309186,26327645,0.729400,Undifined,13-01-2019,0.943,0.996,1.000,0.999,0.643
751,752,listings,25302548,26019773,0.723355,Undifined,13-01-2019,1.000,0.999,1.000,0.987,0.632
755,756,listings,23728637,23728515,0.720918,Undifined,13-01-2019,0.884,0.996,0.874,1.000,0.653
757,758,listings,30486511,30357403,0.720829,Undifined,13-01-2019,1.000,0.990,0.439,0.984,0.704
759,760,listings,30394946,30394793,0.718490,Undifined,13-01-2019,1.000,1.000,0.667,0.985,0.670
763,764,listings,27080314,27080292,0.717206,Undifined,13-01-2019,0.919,0.992,0.000,0.989,0.763
765,766,listings,30970985,30971152,0.716489,Undifined,13-01-2019,0.963,1.000,0.361,0.994,0.710
773,774,listings,28198065,28196365,0.712046,Undifined,13-01-2019,1.000,0.999,0.714,0.991,0.655
782,783,listings,25174255,25157473,0.708024,Undifined,13-01-2019,0.872,1.000,0.232,0.990,0.722
784,785,listings,25789967,24831343,0.708007,Undifined,13-01-2019,0.889,0.982,0.938,0.979,0.629
786,787,listings,28614590,28738248,0.706967,Undifined,13-01-2019,1.000,0.990,0.375,0.997,0.694
790,791,listings,28800971,28797187,0.705637,Undifined,13-01-2019,0.969,0.984,0.733,0.976,0.648
792,793,listings,30374406,30823357,0.705331,Undifined,13-01-2019,1.000,0.998,0.259,0.996,0.706
794,795,listings,30784439,30784527,0.704597,Undifined,13-01-2019,1.000,1.000,0.510,0.983,0.673
800,801,listings,23047886,23048836,0.701865,Undifined,13-01-2019,0.933,1.000,1.000,0.997,0.607

In [21]:
df_listings[df_listings['id']== 22556265]

,id,listing_url,name,description,host_id,host_name,neighbourhood_cleansed,latitude,longitude,room_type,accommodates,bathrooms,bedrooms,beds,price
15096,22556265,https://www.airbnb.com/rooms/22556265,Central & cosy ground floor stay Vondelpark 1,This cosy and central stay is located at the V...,165633227,Anisha,De Baarsjes - Oud-West,52.359363,4.858259,Private room,1,1.0,1.0,1.0,68.0

In [22]:

df_listings[df_listings['id']== 22556393]

,id,listing_url,name,description,host_id,host_name,neighbourhood_cleansed,latitude,longitude,room_type,accommodates,bathrooms,bedrooms,beds,price
15097,22556393,https://www.airbnb.com/rooms/22556393,Central & cosy ground floor stay Vondelpark 2,This cosy and central stay is located at the V...,165633227,Anisha,De Baarsjes - Oud-West,52.359348,4.857868,Private room,1,1.0,1.0,1.0,68.0

## JSON File

In [20]:
output.to_json('duplicates.js' ,orient='records')